"""empty message

Revision ID: 0b45daa30f78
Revises: 61b8910c8290
Create Date: 2025-03-16 17:40:06.842691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b45daa30f78'
down_revision = '61b8910c8290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.drop_constraint('tags_tag_name_key', type_='unique')
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_column('tag_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('tags_tag_name_key', ['tag_name'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###
