"""empty message

Revision ID: 845611d2f734
Revises: 6cf34e202492
Create Date: 2025-03-16 17:07:42.756806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '845611d2f734'
down_revision = '6cf34e202492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('avatar', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artista')
    # ### end Alembic commands ###
