"""empty message

Revision ID: a6743539216e
Revises: aebc55055c29
Create Date: 2025-04-14 19:00:10.167026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6743539216e'
down_revision = 'aebc55055c29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coments', schema=None) as batch_op:
        batch_op.drop_constraint('coments_wallpaper_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'wallpaper', ['wallpaper_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.drop_constraint('favoritos_id_wallpaper_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'wallpaper', ['id_wallpaper'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('me_gusta', schema=None) as batch_op:
        batch_op.drop_constraint('me_gusta_id_wallpaper_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'wallpaper', ['id_wallpaper'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('tags_wallpaper', schema=None) as batch_op:
        batch_op.drop_constraint('tags_wallpaper_id_wallpaper_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'wallpaper', ['id_wallpaper'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags_wallpaper', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tags_wallpaper_id_wallpaper_fkey', 'wallpaper', ['id_wallpaper'], ['id'])

    with op.batch_alter_table('me_gusta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('me_gusta_id_wallpaper_fkey', 'wallpaper', ['id_wallpaper'], ['id'])

    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favoritos_id_wallpaper_fkey', 'wallpaper', ['id_wallpaper'], ['id'])

    with op.batch_alter_table('coments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('coments_wallpaper_id_fkey', 'wallpaper', ['wallpaper_id'], ['id'])

    # ### end Alembic commands ###
