"""empty message

Revision ID: a9acbf0909af
Revises: e1bf4146de2c
Create Date: 2025-03-16 08:42:37.328017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9acbf0909af'
down_revision = 'e1bf4146de2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fan', schema=None) as batch_op:
        batch_op.drop_constraint('fan_avatar_key', type_='unique')
        batch_op.drop_constraint('fan_description_key', type_='unique')
        batch_op.drop_constraint('fan_password_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fan', schema=None) as batch_op:
        batch_op.create_unique_constraint('fan_password_key', ['password'])
        batch_op.create_unique_constraint('fan_description_key', ['description'])
        batch_op.create_unique_constraint('fan_avatar_key', ['avatar'])

    # ### end Alembic commands ###
