"""empty message

Revision ID: aebc55055c29
Revises: 
Create Date: 2025-04-14 17:13:34.696054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aebc55055c29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('avatar', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('fan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('avatar', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('seguidores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fan_id', sa.Integer(), nullable=False),
    sa.Column('artista_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artista_id'], ['artista.id'], ),
    sa.ForeignKeyConstraint(['fan_id'], ['fan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallpaper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imagen', sa.String(length=120), nullable=False),
    sa.Column('fecha', sa.String(length=200), nullable=True),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('artista_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artista_id'], ['artista.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('coments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=120), nullable=False),
    sa.Column('fan_id', sa.Integer(), nullable=False),
    sa.Column('wallpaper_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fan_id'], ['fan.id'], ),
    sa.ForeignKeyConstraint(['wallpaper_id'], ['wallpaper.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_fan', sa.Integer(), nullable=False),
    sa.Column('id_wallpaper', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_fan'], ['fan.id'], ),
    sa.ForeignKeyConstraint(['id_wallpaper'], ['wallpaper.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('me_gusta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_fan', sa.Integer(), nullable=False),
    sa.Column('id_wallpaper', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_fan'], ['fan.id'], ),
    sa.ForeignKeyConstraint(['id_wallpaper'], ['wallpaper.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags_wallpaper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_tag', sa.Integer(), nullable=False),
    sa.Column('id_wallpaper', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_tag'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['id_wallpaper'], ['wallpaper.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags_wallpaper')
    op.drop_table('me_gusta')
    op.drop_table('favoritos')
    op.drop_table('coments')
    op.drop_table('wallpaper')
    op.drop_table('seguidores')
    op.drop_table('user')
    op.drop_table('tags')
    op.drop_table('fan')
    op.drop_table('artista')
    # ### end Alembic commands ###
