"""empty message

Revision ID: db6c39aa629c
Revises: 96e383e11f78
Create Date: 2025-03-29 20:57:45.785214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db6c39aa629c'
down_revision = '96e383e11f78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallpaper', schema=None) as batch_op:
        batch_op.drop_constraint('wallpaper_nombre_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallpaper', schema=None) as batch_op:
        batch_op.create_unique_constraint('wallpaper_nombre_key', ['nombre'])

    # ### end Alembic commands ###
